### ISSUE TITLE
Issue while flashing 

### ISSUE THREAD

**Issue by Dhruv-Sapra** [SuperChamp234/wifi-bot-sra#1]
While flashing on ESP-32, WE GOT THIS BIG ISSUE
![Screenshot from 2022-12-09 16-27-46](https://user-images.githubusercontent.com/111555972/206687546-4265208d-6971-4221-a0e7-913b208c1222.png)
Please, correct this ASAP we want to flash this for tomorrow's exhibiton.

**Comment by SuperChamp234** [comment]
Updated Readme in latest commit, marking as solved
